trailing_comma:
  mandatory_comma: true
opening_brace:
  allow_multiline_func: true
nesting:
  type_level: 3
excluded:
  - Carthage
  - Pods
disabled_rules:
  - closure_parameter_position
  - identifier_name
  - force_try
  - todo
