nesting:
  type_level: 3
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - stationTests
  - Package
disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - force_try
  - closure_parameter_position
