json:
  - inputs: ./station.localization/station.localization.json
    outputs:
      - templatePath: ./Common/RuuviLocalization/Templates/Localizable_en.strings.stencil
        output: ./Common/RuuviLocalization/Sources/Resources/en.lproj/Localizable.strings
  - inputs: ./station.localization/station.localization.json
    outputs:
      - templatePath: ./Common/RuuviLocalization/Templates/Localizable_sv.strings.stencil
        output: ./Common/RuuviLocalization/Sources/Resources/sv.lproj/Localizable.strings
  - inputs: ./station.localization/station.localization.json
    outputs:
      - templatePath: ./Common/RuuviLocalization/Templates/Localizable_ru.strings.stencil
        output: ./Common/RuuviLocalization/Sources/Resources/ru.lproj/Localizable.strings
  - inputs: ./station.localization/station.localization.json
    outputs:
      - templatePath: ./Common/RuuviLocalization/Templates/Localizable_fi.strings.stencil
        output: ./Common/RuuviLocalization/Sources/Resources/fi.lproj/Localizable.strings
  - inputs: ./station.localization/station.localization.json
    outputs:
      - templatePath: ./Common/RuuviLocalization/Templates/Localizable_fr.strings.stencil
        output: ./Common/RuuviLocalization/Sources/Resources/fr.lproj/Localizable.strings
  - inputs: ./station.localization/station.localization.json
    outputs:
      - templatePath: ./Common/RuuviLocalization/Templates/Localizable_de.strings.stencil
        output: ./Common/RuuviLocalization/Sources/Resources/de.lproj/Localizable.strings