trailing_comma:
  mandatory_comma: true
opening_brace:
  ignore_multiline_function_signatures: true
nesting:
  type_level: 3
excluded:
  - Carthage
  - Pods
  - Packages
disabled_rules:
  - closure_parameter_position
  - identifier_name
  - force_try
  - todo
  - multiple_closures_with_trailing_closure
