BUILD_NUMBER: &BUILD_NUMBER 1
APP_VERSION: &APP_VERSION 2.5.2
PROJECT_NAME: &PROJECT_NAME Ruuvi
DEVELOPMENT_TEAM: &DEVELOPMENT_TEAM 4MUYJ4YYH4
BUNDLE_ID_PREFIX: &BUNDLE_ID_PREFIX com.ruuvi

attributes:
  ORGANIZATIONNAME: Ruuvi Innovations Oy

settings:
  base:
    CURRENT_PROJECT_VERSION: *BUILD_NUMBER
    MARKETING_VERSION: *APP_VERSION
    DEVELOPMENT_TEAM: *DEVELOPMENT_TEAM

name: *PROJECT_NAME

options:
  bundleIdPrefix: *BUNDLE_ID_PREFIX
  developmentLanguage: en
  deploymentTarget:
    iOS: 14.0

targetTemplates:
  Framework:
    name: "${target_name}"
    type: framework
    platform: iOS
    info:
      path: Packages/${target_name}/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
    settings:
      base:
        DEVELOPMENT_TEAM: *DEVELOPMENT_TEAM
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        PRODUCT_BUNDLE_IDENTIFIER: com.ruuvi.station.${target_name}
        PRODUCT_NAME: "${target_name}"
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        MERGEABLE_LIBRARY: false
  Module:
    name: "${target_name}"
    type: framework
    platform: iOS
    info:
      path: Modules/${target_name}/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
    settings:
      base:
        DEVELOPMENT_TEAM: *DEVELOPMENT_TEAM
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        PRODUCT_BUNDLE_IDENTIFIER: com.ruuvi.station.${target_name}
        PRODUCT_NAME: "${target_name}"
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        MERGEABLE_LIBRARY: false
  CommonFramework:
    name: "${target_name}"
    type: framework
    platform: iOS
    info:
      path: Common/${target_name}/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
    settings:
      base:
        DEVELOPMENT_TEAM: *DEVELOPMENT_TEAM
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        PRODUCT_BUNDLE_IDENTIFIER: com.ruuvi.station.${target_name}
        PRODUCT_NAME: "${target_name}"
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        MERGEABLE_LIBRARY: false
packages:
  BTKit:
    url: https://github.com/ruuvi/BTKit
    from: 0.5.1
  Charts:
    url: https://github.com/danielgindi/Charts
    from: 4.1.0
  LightRoute:
    url: https://github.com/rinat-enikeev/LightRoute
    from: 2.2.2
  Swinject: 
    url: https://github.com/Swinject/Swinject
    from: 2.8.3
  Firebase: 
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.18.0
  RangeSeekSlider:
    url: https://github.com/rinat-enikeev/RangeSeekSlider
    from: 1.8.2
  GestureInstructions:
    url: https://github.com/rinat-enikeev/GestureInstructions
    from: 0.0.2
  Humidity:
    url: https://github.com/rinat-enikeev/Humidity
    from: 0.1.5
  Future:
    url: https://github.com/kean/Future
    from: 1.3.0
  NordicDFU:
    url: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library
    from: 4.10.3
  KeychainAccess: 
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.2.1
  GRDB: 
    url: https://github.com/groue/GRDB.swift
    from: 4.14.0
  FLEX: 
    url: https://github.com/FLEXTool/FLEX.git
    from: 5.22.10

include:
- Packages/RuuviAnalytics/target.yml
- Packages/RuuviCloud/target.yml
- Packages/RuuviContext/target.yml
- Packages/RuuviCore/target.yml
- Packages/RuuviDaemon/target.yml
- Packages/RuuviDFU/target.yml
- Packages/RuuviLocal/target.yml
- Packages/RuuviMigration/target.yml
- Packages/RuuviNotification/target.yml
- Packages/RuuviNotifier/target.yml
- Packages/RuuviOntology/target.yml
- Packages/RuuviPersistence/target.yml
- Packages/RuuviPool/target.yml
- Packages/RuuviReactor/target.yml
- Packages/RuuviRepository/target.yml
- Packages/RuuviService/target.yml
- Packages/RuuviStorage/target.yml
- Packages/RuuviUser/target.yml
- Common/RuuviPresenters/target.yml
- Common/RuuviLocalization/target.yml
- Modules/RuuviDiscover/target.yml
- Modules/RuuviOnboard/target.yml
- Modules/RuuviFirmware/target.yml
- Apps/RuuviStation/target.yml
- Apps/RuuviStation/Widgets/target.yml
- Apps/RuuviStation/NotificationService/target.yml
- Apps/RuuviStation/Intents/target.yml

configs:
  Alpha: debug
  Debug: debug
  Release: release