import UIKit

enum RuuviAssets {
    static let alertActiveImage = UIImage(named: "icon-alert-active")
    static let alertOffImage = UIImage(named: "icon-alert-off")
    static let alertOnImage = UIImage(named: "icon-alert-on")
    static let backButtonImage = UIImage(named: "chevron_back")
    static let closeButtonImage = UIImage(named: "dismiss-modal-icon")
    static let threeDotMoreImage = UIImage(named: "more_3dot")
    static let cardsIcon = UIImage(named: "icon-cards-button")
    static let chartsIcon = UIImage(named: "icon-charts-button")
    static let settingsIcon = UIImage(named: "baseline_settings_white_48pt")
    static let signInBgLayer = UIImage(named: "sign_in_bg_layer")
    static let signInBeaver = UIImage(named: "beaver-mail")
    static let advertisementImage = UIImage(named: "icon-bluetooth")
    static let heartbeatImage = UIImage(named: "icon-bluetooth-connected")
    static let ruuviNetworkImage = UIImage(named: "icon-gateway")
    static let weatherProviderImage = UIImage(named: "icon-weatherstation")
    static let humidityImage = UIImage(named: "icon-measure-humidity")
    static let pressureImage = UIImage(named: "icon-measure-pressure")
    static let movementCounterImage = UIImage(named: "icon-measure-movement")
    static let locationImage = UIImage(named: "icon-measure-location")
    static let editPenImage = UIImage(named: "edit_pen")
    static let dropDownArrowImage = UIImage(named: "arrow_drop_down")
}
