name: Checks for opened PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    name: SwiftLint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
